Add SIP-2CEM
binance-chain/tokens-info pull request #121
Opened 2020-09-27 16:15 UTC by arbitrxfund

{ 
    "asset":"SIP-2CEM",
    "assetMap":"SIP",
    "market": "ALTS",
    "officialSiteUrl":"https://arbitrx.fund/",
    "contactEmail":"info@arbitrx.fund",
    "display":true,
  "contact": {
    "Telegram": "https://t.me/arbitrxfund",
    "Medium": "https://medium.com/@arbitrxfund",
    "Twitter": "https://twitter.com/arbitrxfund",
    "Github": "https://github.com/arbitrxfund",
    
  }
}
![SIP-2CEM](https://user-images.githubusercontent.com/70487865/94369999-524ab480-00aa-11eb-930e-e9947c3ac728.png)

2020-09-27 20:04 UTC, arbitrxfund commented
Kindly Add this

2020-09-28 03:02 UTC, huangsuyu requested changes
json file is not under the correct format, please check again.

2020-09-28 03:12 UTC, arbitrxfund reviewed
Updated

2020-09-28 03:57 UTC, huangsuyu approved these changes

2020-09-28 03:57 UTC, merged