add JSB token
binance-chain/tokens-info pull request #126
Opened 2020-10-27 19:24 UTC by jsbgith

2020-10-27 19:33 UTC, jsbgith commented
add updated JSB-614M token

2020-10-27 19:35 UTC, kolya-t submitted a review, later dismissed

2020-10-29 03:12 UTC, huangsuyu requested changes
Please add 
  "market": "ALTS",

2020-11-05 11:40 UTC, jsbgith commented
@huangsuyu can you please review and merge?

2020-11-06 02:35 UTC, huangsuyu approved these changes

2020-11-06 02:36 UTC, merged